### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by Vivian0210** [machinelearningmindset/machine-learning-course#32]
Hi @astorfi ,
Thanks for your great work ! My friends and I have learned a lot here.
China has a platform called KESCI (https://www.kesci.com). They provide algorithm competition opportunities for developers, which is similar to Kaggle, and self - training online environment to enhance their algorithmic ability.
I am going to translate the whole series to Chinese and applied for a column to publish them on KESCI, as a series. Hope to get your permission.
thanks.

**Comment by astorfi** [comment]
@Vivian0210 Thanks for requesting for the permission.
Would you please email me at (amirsina.torfi@gmail.com) to further discuss the scope of your work?

Thanks

**Comment by Vivian0210** [comment]
With Pleasure!
