### ISSUE TITLE
Naive bayes question

### ISSUE THREAD

**Issue by suedroplet** [machinelearningmindset/machine-learning-course#33]
Hi @astorfi ,
Thanks for your great work !
 I'm a beginner of ML. Tonight when I learn ***Naive Bayes Classification*** in your tutorial, I found the **Equation 1** in the tutorial is different from that in Wiki.  I wonder which one is correct or both of them are right?

![image](https://user-images.githubusercontent.com/30567037/58331772-71a95000-7e6c-11e9-90bc-ca348d97f1fe.png)

-------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/30567037/58331805-7ff76c00-7e6c-11e9-9301-b8c7f474f28a.png)

Look forward to your reply.

**Comment by astorfi** [comment]
@suedroplet Thank you so much for your observation. Yes, there is a mistake in our tutorial regarding that formula and you are absolutely correct.

@b-sherman Would you please correct this issue?

**Comment by b-sherman** [comment]
Hi @suedroplet,
Thanks for catching that mistake. The Wikipedia version is correct. I will update the image shortly.
